export const dataset = [
    {
      london: 59,
      paris: 57,
      newYork: 86,
      profitPercent: 21,
      month: '1',
    },
    {
      london: 50,
      paris: 52,
      newYork: 78,
      profitPercent: 28,
      month: '2',
    },
    {
      london: 47,
      paris: 53,
      newYork: 106,
      profitPercent: 41,
      month: '3',
    },
    {
      london: 54,
      paris: 56,
      newYork: 92,
      profitPercent: 73,
      month: '4',
    },
    {
      london: 57,
      paris: 69,
      newYork: 92,
      profitPercent: 99,
      month: '5',
    },
    {
      london: 60,
      paris: 63,
      newYork: 103,
      profitPercent: 144,
      month: '6',
    },
    {
      london: 59,
      paris: 60,
      newYork: 105,
      profitPercent: 319,
      month: '7',
    },
    {
      london: 65,
      paris: 60,
      newYork: 106,
      profitPercent: 249,
      month: '8',
    },
    {
      london: 51,
      paris: 51,
      newYork: 95,
      profitPercent: 131,
      month: '9',
    },
    {
      london: 60,
      paris: 65,
      newYork: 97,
      profitPercent: 55,
      month: '10',
    },
    {
      london: 67,
      paris: 64,
      newYork: 76,
      profitPercent: 48,
      month: '11',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 87,
      month: '12',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 91,
      month: '13',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 53,
      month: '14',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 232,
      month: '15',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 251,
      month: '16',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 65,
      month: '17',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 125,
      month: '18',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 115,
      month: '19',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 285,
      month: '20',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 185,
      month: '21',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 25,
      month: '22',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 445,
      month: '23',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 105,
      month: '24',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 75,
      month: '25',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 250,
      month: '26',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 325,
      month: '27',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 350,
      month: '28',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 212,
      month: '29',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      profitPercent: 125,
      month: '30',
    },
  ];